site_name: 植创社

theme:
  name: material
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: green
      accent: green
      scheme: default
      toggle:
        icon: material//weather-sunny
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      primary: green
      accent: green
      scheme: slate
      toggle:
        icon: material/weather-night
        name: 切换到浅色模式
  features:
    - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

markdown_extensions:
  - attr_list
  - def_list

plugins:
  - blog

copyright: Copyright &copy; 2025 植创社 <br> <a href="https://beian.miit.gov.cn/" target="_blank">浙ICP备2024119342号-2</a>

nav:
  - 首页: index.md
  - 动态:
      - blog/index.md
